[package]
name = "aba-avner"
version = "0.1.1"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/tomerdev1/aba-avner"

[build-dependencies]
tauri-build = { version = "2.5.5", features = [] }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
walkdir = "2.5"
rayon = "1.8"
log = "0.4"
image = { version = "0.24", default-features = false, features = ["png", "jpeg", "gif", "bmp", "tiff", "webp"] }
tauri = { version = "2.10.2", optional = true , features = ["protocol-asset"] }
tauri-plugin-dialog = { version = "2.6.0", optional = true }
tauri-plugin-updater = { version = "2.10.1", optional = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_Storage_Packaging_Appx"] }

[dev-dependencies]
tempfile = "3.10"

[features]
default = ["gui"]
gui = ["tauri", "tauri-plugin-dialog", "tauri-plugin-updater"]
custom-protocol = ["gui", "tauri/custom-protocol"]

[[bin]]
name = "aba-avner"
path = "src/main.rs"
required-features = ["gui"]
